//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StausBoardDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int ComponentId { get; set; }
        public int PartPartId { get; set; }
        public string SerialNumber { get; set; }
        public int EquipmentEquipmentId { get; set; }
    }
}
