//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StausBoardDatabase
{
    using System;
    
    public enum EquipmentStatus : byte
    {
        Operational = 0,
        Degraded = 1,
        ScheduledOutage = 2,
        UnscheduledOutage = 3
    }
}
