//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StausBoardDatabase
{
    using System;
    
    public enum OperationalStatus : byte
    {
        OnLine = 0,
        OffLine = 1,
        HotStandBy = 2,
        ColdStandBy = 3,
        LayUp = 4
    }
}
