//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StausBoardDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutageStatus
    {
        public int OutageStatusId { get; set; }
        public string Status { get; set; }
        public string Timestamp { get; set; }
        public string Tech { get; set; }
    }
}
