//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StausBoardDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutageNote
    {
        public int OutageNoteId { get; set; }
        public int OutageOutageId { get; set; }
        public int OutageOutageId1 { get; set; }
    }
}
