//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StausBoardDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageGroup()
        {
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int PageGroupId { get; set; }
        public int StatusPageStausPageId { get; set; }
        public string Name { get; set; }
        public EquipmentStatus EquipmentStatus { get; set; }
        public OperationalStatus OperationalStatus { get; set; }
        public int StatusPageStausPageId1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment { get; set; }
    }
}
