//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StausBoardDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StatusBoardDatabaseContainer : DbContext
    {
        public StatusBoardDatabaseContainer()
            : base("name=StatusBoardDatabaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment> EquipmentCollection { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<Outage> Outages { get; set; }
        public virtual DbSet<OutageNote> OutageNotes { get; set; }
        public virtual DbSet<StatusPage> StatusPages { get; set; }
        public virtual DbSet<PageGroup> PageGroups { get; set; }
    }
}
